### ISSUE TITLE
Add basic css/js

### ISSUE THREAD

**Issue by m-anish** [eka-foundation/cham#1]
Add the most basic js/css to make it look like not-a-demo-page.

**Comment by so-ale** [comment]
basic css has been added. see if this works.

**Comment by m-anish** [comment]
Looks good. Can you very quickly test on a mobile to see if it is okay-ish?

**Comment by so-ale** [comment]
"/" were removed from relative links of linked css and js files in index.html to make it work on my Windows machine. Let me know if this is causing problem when hosted on the server.

**Comment by m-anish** [comment]
Seems to work just fine here on firefox/ubuntu

**Comment by m-anish** [comment]
Good enough for now! Closing.
